ARG REGISTRY=docker.io
ARG IMAGE_TAG=0.0.1-workstation
ARG ORG=ensono

ARG DECK_VERSION=1.36.0
ARG PORTAL_CLI_VERSION=1.2.0

FROM ${REGISTRY}/${ORG}/eir-foundation-powershell:${IMAGE_TAG}

COPY files/install.sh /usr/local/bin/install.sh

RUN chmod +x /usr/local/bin/unittests.sh && \
    chmod +x /usr/local/bin/install.sh && \
    bash /usr/local/bin/install.sh
