import:
- ./build/taskctl/contexts.yaml
- ./build/taskctl/tasks.yaml

pipelines:

  setup:
  - task: build:number

  build:base:
  - task: build:container
    variables:
      IMAGE_NAME: williamamido/runner-pwsh
      DOCKERFILE: ./image_definitions/base

  build:dotnet:
  - task: build:container
    variables:
      IMAGE_NAME: williamamido/runner-pwsh-dotnet
      DOCKERFILE: ./image_definitions/dotnet

  build:java:
  - task: build:container
    variables:
      IMAGE_NAME: williamamido/runner-pwsh-java
      DOCKERFILE: ./image_definitions/java

  publish: 
  - task: update:dashboard

  build:
    - pipeline: setup
    - pipeline: build:base
      depends_on: [setup]
    - pipeline: build:dotnet
      depends_on: [setup,build:base]
    - pipeline: build:java
      depends_on: [setup,build:base]
    - pipeline: publish
      depends_on: [build:base,build:java,build:dotnet]