import:
- ./build/taskctl/contexts.yaml
- ./build/taskctl/tasks.yaml

pipelines:

  setup:
  - task: build:number

  build:base:
  - task: build:container
    variables:
      IMAGE_NAME: amidostacks/runner-pwsh
      DOCKER_BUILD_ARGS: -f ./image_definitions/base/Dockerfile.alpine ./image_definitions/base

  build:dotnet:
  - task: build:container
    variables:
      IMAGE_NAME: amidostacks/runner-pwsh-dotnet
      DOCKER_BUILD_ARGS: -f ./image_definitions/dotnet/Dockerfile.alpine ./image_definitions/dotnet

  build:java:
  - task: build:container
    variables:
      IMAGE_NAME: amidostacks/runner-pwsh-java
      DOCKER_BUILD_ARGS: -f ./image_definitions/java/Dockerfile.alpine ./image_definitions/java

  build:python:
  - task: build:container
    variables:
      IMAGE_NAME: amidostacks/runner-pwsh-python
      DOCKER_BUILD_ARGS: -f ./image_definitions/python/Dockerfile.alpine ./image_definitions/python

  build:golang:
  - task: build:container
    variables:
      IMAGE_NAME: amidostacks/runner-pwsh-golang
      DOCKER_BUILD_ARGS: -f ./image_definitions/golang/Dockerfile.alpine ./image_definitions/golang

  build:asciidoctor:
  - task: build:container
    variables:
      IMAGE_NAME: amidostacks/runner-pwsh-asciidoctor
      DOCKER_BUILD_ARGS: -f ./image_definitions/asciidoctor/Dockerfile.alpine ./image_definitions/asciidoctor

  publish:
  - task: update:dashboard

  all: # Simulating a full run of the CI/CD tool.
  - pipeline: setup
  - pipeline: build:base
    depends_on: [setup]
  - pipeline: build:java
    depends_on: [build:base]
  - pipeline: build:dotnet
    depends_on: [build:java]
  - pipeline: build:python
    depends_on: [build:base]
  - pipeline: build:golang
    depends_on: [build:base]
  - pipeline: build:asciidoctor
    depends_on: [build:base]
  - pipeline: publish
    depends_on: [build:base, build:dotnet, build:java, build:python, build:golang, build:asciidoctor]
