import:
- ./build/taskctl/contexts.yaml
- ./build/taskctl/tasks.yaml

pipelines:

  setup:
  - task: build:number

  build:base:
  - task: build:container
    variables:
      IMAGE_NAME: amidostacks/runner-pwsh
      DOCKERFILE: ./image_definitions/base/Dockerfile.alpine

  build:dotnet:
  - task: build:container
    variables:
      IMAGE_NAME: amidostacks/runner-pwsh-dotnet
      DOCKERFILE: ./image_definitions/dotnet/Dockerfile.alpine

  build:java:
  - task: build:container
    variables:
      IMAGE_NAME: amidostacks/runner-pwsh-java
      DOCKERFILE: ./image_definitions/java/Dockerfile.alpine

  build:python:
  - task: build:container
    variables:
      IMAGE_NAME: amidostacks/runner-pwsh-python
      DOCKERFILE: ./image_definitions/python/Dockerfile.alpine

  build:golang:
  - task: build:container
    variables:
      IMAGE_NAME: amidostacks/runner-pwsh-golang
      DOCKERFILE: ./image_definitions/golang

  build:asciidoctor:
  - task: build:container
    variables:
      IMAGE_NAME: amidostacks/runner-pwsh-asciidoctor
      DOCKERFILE: ./image_definitions/asciidoctor/Dockerfile.alpine

  publish:
  - task: update:dashboard

  all: # Simulating a full run of the CI/CD tool.
  - pipeline: setup
  - pipeline: build:base
    depends_on: [setup]
  - pipeline: build:dotnet
    depends_on: [build:base]
  - pipeline: build:java
    depends_on: [build:base]
  - pipeline: build:python
    depends_on: [build:base]
  - pipeline: build:golang
    depends_on: [build:base]
  - pipeline: build:asciidoctor
    depends_on: [build:base]
  - pipeline: publish
    depends_on: [build:base, build:dotnet, build:java, build:python, build:golang, build:asciidoctor]
