ARG REGISTRY=docker.io
ARG IMAGE_TAG=0.0.1-workstation
ARG ORG=ensono

FROM ${REGISTRY}/${ORG}/eir-foundation-powershell:${IMAGE_TAG}

# Specify the versions of software to install
ARG NVM_VERSION=0.39.7
ARG NODE_VERSIONS="v20.12.0,v18.20.0"

# Copy the necessary files to the image
COPY files/install.sh /tmp/install.sh
RUN chmod +x /tmp/install.sh && /tmp/install.sh
