ARG REGISTRY=docker.io
ARG IMAGE_TAG=0.0.1-workstation
ARG ORG=ensono

FROM ${REGISTRY}/${ORG}/eir-foundation-powershell:${IMAGE_TAG}

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install iptables=1.8.11-2ubuntu3 procps=2:4.0.4-9ubuntu1 kmod=34.2-2ubuntu2
    
RUN update-alternatives --set iptables /usr/sbin/iptables-legacy
RUN update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
COPY ./files/validating-script.sh /
RUN chmod +x /validating-script.sh
ENTRYPOINT ["bash", "/validating-script.sh"]
