ARG REGISTRY=docker.io
ARG IMAGE_TAG=0.0.1-workstation
ARG ORG=ensono

FROM ${REGISTRY}/${ORG}/eir-foundation-azure-cli

# Run the install script to get the additional commands
COPY files/install.sh /tmp/install.sh
COPY files/requirements.txt /tmp/requirements.txt

RUN chmod +x /tmp/install.sh && /tmp/install.sh 

