ARG UBUNTU_VERSION=22.04

FROM ubuntu:${UBUNTU_VERSION}

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install iptables=1.8.7-1ubuntu5.2

RUN update-alternatives --set iptables /usr/sbin/iptables-legacy
RUN update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
COPY ./files/bootstrap-script.sh /
RUN chmod +x /bootstrap-script.sh
ENTRYPOINT ["/bootstrap-script.sh"]
