ARG REGISTRY=docker.io
ARG IMAGE_TAG=0.0.1-workstation
ARG ORG=ensono

FROM ${REGISTRY}/${ORG}/eir-foundation-powershell:${IMAGE_TAG}

ARG AZURE_CLI_VERSION=2.48.1

# Install the Azure CLI application
COPY files/install.bash /usr/local/bin/install.bash
RUN chmod +x /usr/local/bin/install.bash && /usr/local/bin/install.bash
