== EIR Foundation PowerShell

This Docker image is the foundation image from which all other EIR images are built from. It is not intended to be used directly as a container image, but there is no restriction on doing so.

The image is built from Ubuntu, PowerShell and the EnsonoBuild PowerShell module are installed.

During the build of the image a profile file for PowerShell is copied in. The profile file is copied to `/opt/microsoft/powershell/7/Microsoft.PowerShell_profile.ps1`.

The profile sets the following things in the session:

[cols="2,3,1",options="header",stripe=even]
|===
| Variable | Description | Value
| `InformationPreference` | States how messages that are written out to the console using `Write-Information` are handled.

By default such messages are hidden, this is changed to `Continue` so that they are displayed.
| Continue
| `ErrorActionPreference` | States how errors are handled.

In this case any error that occurs will be displayed to the console. | Stop
| `PSNativeCommandErrorActionPreference` | Allows command line application errors to be treated more like PowerShell errors.

This is available in PowerShell 7.3 an above.

https://matthorgan.xyz/blog/powershell-handling-native-applications/ | $true
|===

=== Specs

**Platforms**: `linux/amd64`, `linux/arm64`

**Base Image**: ubuntu:22.04

==== Software

[cols="1,2,1,2",options=header]
|====
| Type | Name | Version | URL
| Binary | PowerShell | 7.4.1 | https://github.com/PowerShell/PowerShell
| Module | EnsonoBuild | 1.0.43 | https://github.com/Ensono/independent-runner
| Binary | Taskctl | 1.5.3 | https://github.com/Ensono/taskctl
|====
