== EIR Foundation PowerShell

This Docker image is the foundation image from which all other EIR images are built from. It is not intended to be used directly as a container image, but there is no restriction on doing so.

The image is built from Ubuntu, PowerShell and the EnsonoBuild PowerShell module are installed.

During the build of the image a profile file for PowerShell is copied in. This sets the PSModulePath globally so that the EnsonoBuild module is always available without having to pass the environment variables in the Docker command line arguments.

The profile file is copied to `/opt/microsoft/powershell/7/Microsoft.PowerShell_profile.ps1`

=== Specs

**Platforms**: `linux/amd64`, `linux/arm64`

**Base Image**: ubuntu:22.04

==== Software

[cols="1,2,1,2",options=header]
|====
| Type | Name | Version | URL
| Binary | PowerShell | 7.4.1 | https://github.com/PowerShell/PowerShell
| Module | EnsonoBuild | 1.0.43 | https://github.com/Ensono/independent-runner
| Binary | Taskctl | 1.5.3 | https://github.com/Ensono/taskctl
|====
