== EIR NodeJS

This Docker image installs the Node Version Manager (NVM) tool so that multiple versions of NodeJS can be installed and used. Two versions of the application installed.

The latest version of NodeJS is set as the default version.

In addition to `nvm` a PowerShell version of the same tool is installed, https://github.com/aaronpowell/ps-nvm[PS-NVM]. The `nvm` tool only works for `bash`, however this tool allows for the same functionality in PowerShell. It is installed using the `install.ps1` file which then generates  a file in the image to state where the Node versions has been installed to by `nvm`.

Profile file: `"/opt/microsoft/powershell/7/Microsoft.PowerShell_profile.ps1"`

The script also updates the global profile file so that the default version of NodeJS is set.

NOTE: We do not use the PS-NVM to install NodeJS, that task is performed by the Bash version of the tool.

=== Specs

**Platforms**: `linux/amd64`, `linux/arm64`

**Base Image**: ensono/eir-fondation-powershell

==== Software

[cols="1,2,1,2,2",options=header]
|====
| Type | Name | Version | URL (X64) | URL (ARM64)
| Javascript | NVM | 0.39.7 2+| https://github.com/nvm-sh/nvm
| PowerShell | PS-NVM | 2.5.4 2+| https://github.com/aaronpowell/ps-nvm
| Binary | NodeJS | 18.20.2 | https://nodejs.org/dist/v18.20.2/node-v18.20.2-linux-x64.tar.xz | https://nodejs.org/dist/v18.20.2/node-v18.20.2-linux-arm64.tar.xz
| Binary | NodeJS | 20.16.0 | https://nodejs.org/dist/v20.16.0/node-v20.16.0-linux-x64.tar.xz | https://nodejs.org/dist/v20.16.0/node-v20.16.0-linux-arm64.tar.xz
|====
