== Building Images

As seen in the <<docker-image-dependencies>> image, all of the Docker images that are built for use with the Independent Runner are based on a hierarchy. This means that they need to be built in the correct order. All of the tasks are set in Taskctl.

Although the build process uses the `taskctl` command line tool and some aspects of the Independent Runner are used, the Docker images are **not** used to build the images. The reason for this is to avoid a circular dependency on the images as they are being built.

Due to the requirement to build without using container images and needing to produce images for multiple platforms, there are a couple of disadvantages:

* When building locally, the necessary tools all need to be installed
* Depending on the Docker engine being used, the way in which the images are built differ.

IMPORTANT: This goes against the ethos of the Independent Runner in running the same commands on any system. Please see <<Multi Platform Builds>> for more information.

include::build/multiplatform.adoc[]

include::build/locally.adoc[]

include::build/cicd.adoc[]

