---
linkTitle: {name} Image
---

=== {name} Image

Inspec is on the of the tools that we are working with to perform Infrastructure testing. The official installer for Inspec will not work with Alpine OS, so to get around this the image installs Ruby and then installs the necessary packages and Gems to be able to install Inspec from a Gem.

.OS Packages
[cols="1,4,1",options="header",stripes=even]
|===
| Name | Description | Removed
| ruby | Programming language used by Inspec | icon:times[]
| ruby-dev | Development libraries required to build the native gems | icon:check[]
| build-base | GCC and other tools required to build the native gems for Inspec | icon:check[]
|===

To install Inspec a number of Gem files are required. These are Inspec requirements and not ones that we have defined.

.Gem Packages
[cols="1,4",options="header",stripes=even]
|===
| Name | Description
| etc | Provides access to information typically stored in UNIX /etc directory.
| bigdecimal | This library provides arbitrary-precision decimal floating-point number class.
| io-console | Add console capabilities to IO instances.
|===

Once all of the necessary packages have been installed, those that have been installed just too compile certain libraries, are removed. Such packages are denoted as "Removed" in the OS Packages table.
